console.log("Hello World!");
console.log("Hello Khalid!");
var personname = "m.khalid khan";
console.log(personname);
var PERSONNAME = "M.KHALID KAHN";
console.log(PERSONNAME);
var PersonName = "M.Khalid Khan";
console.log(PersonName);
var quote = "Ghani Khan once said, Pashtun is not merely a race but in fact a state of mind there is a Pashtun lying inside every man who at times wakes up and overpowers him. The Pashtuns are rain-sown wheat";
console.log(quote);
var AuthorName = "Ghani Khan";
var Quote = "Pashtun is not merely a race but in fact a state of mind there is a Pashtun lying inside every man who at times wakes up and overpowers him. The Pashtuns are rain-sown wheat";
console.log(AuthorName + "once said," + Quote);
var orginal_name = " \t khalid \n";
console.log(orginal_name, "Orginal_Name");
var striped_name = orginal_name.trim();
console.log(striped_name, "Striped Name");
console.log("Addition", 4 + 2);
console.log("Subtraction", 4 - 2);
console.log("Multiplication", 4 * 2);
console.log("Divison", 4 / 2);
